# We need super user level permission to use docker
sudo: required
# Travis CI to be informed that docker should be pre-installed
services:
  - docker 

before_install:
  - docker build -t arjunshah/docker-react -f Dockerfile.dev .

language: generic

script:
  - docker run -e CI=true arjunshah/docker-react npm run test -- --coverage

deploy:
  provider: elasticbeanstalk
  region: "ap-south-1"
  app: "docker-react"
  env: "Dockerreact-env"
  bucket_name: "elasticbeanstalk-ap-south-1-562128230420"
  bucket_path: "docker-react"
  on:
    branch: master
  access_key_id: "$AWS_ACCESS_KEY"
  secret_access_key: "$AWS_SECRET_KEY"